### ISSUE TITLE
Acessing /index.jsp fails

### ISSUE THREAD

**Issue by LuisMichaelis** [pfstrack/eldamo#26]
After trying for serveral hours to get the website to work, i finally found out that i had to download the Gradle 2.6 binaries from their servers instead of using my pre-installed Gradle instance (may be resolved by adding an install script?) because jetty is no more supported since Gradle 4.0 (if i remember correctly). But now i ran into another issue: When trying to access /index.jsp (http://localhost:8080/eldamo/) the server throws this error:

---

HTTP ERROR 500
Problem accessing /eldamo/. Reason:

    PWC6033: Unable to compile class for JSP

PWC6197: An error occurred at line: 14 in the jsp file: /index.jsp
PWC6199: Generated servlet error:
The type java.lang.CharSequence cannot be resolved. It is indirectly referenced from required .class files

Caused by:
org.apache.jasper.JasperException: PWC6033: Unable to compile class for JSP

PWC6197: An error occurred at line: 14 in the jsp file: /index.jsp
PWC6199: Generated servlet error:
The type java.lang.CharSequence cannot be resolved. It is indirectly referenced from required .class files

	at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:123)
	at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:296)
	at org.apache.jasper.compiler.Compiler.generateClass(Compiler.java:376)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:437)
	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:608)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:360)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:486)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:380)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:440)
	at org.mortbay.jetty.servlet.Dispatcher.forward(Dispatcher.java:327)
	at org.mortbay.jetty.servlet.Dispatcher.forward(Dispatcher.java:126)
	at org.mortbay.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:503)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:440)
	at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230)
	at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:926)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)

---

I have Java 1.8 installed and as far as I can tell, compatibility mode for 1.6 is already activated in the build.gradle file. I have not much experience with either Gradle or Jetty so please excuse me if this is a simple problem.

Thank you!

**Comment by pfstrack** [comment]
Hunh. There is so little interest in the code base used to generate Eldamo that this may be the first question I’ve gotten about it!

I vaguely remember seeing that error a couple years ago, but I no longer remember what I did to fix it. I don’t actually run Eldamo from grade myself: a launch it from Eclipse. Maybe you can try doing it that way.

If that doesn’t work, I may need to look at dropping Jetty and figuring out how to run the Eldamo service in Tomcat.

**Comment by pfstrack** [comment]
I took a look at my setup, and I am currently running Eldamo using Java 1.8 in 1.6 compatibility mode, using Eclipse 2018-12 (4.10.0) with the Jetty plugin: Jetty 9.3.12

I suspect the last of these (the Jetty version) is where the problem lies. I think older versions of Jetty may have compatibility problems with new JVMs (some kind of classloader problem). I vaguely remember when I last upgraded my OS and JVM I was also forced to upgrade Jetty.

I haven't run the Jetty plugin from Gradle in many years, so I'm not sure how to get it to work in that setup. I wrote those Gradle instructions back in 2015 and haven't used/updated them since then, because no one has ever asked about them.

I suggest you either (a) run the system from Eclipse with the Jetty version I mentioned above or later, or (b) see if you can coerce Gradle into using a more recent Jetty version. If you are feeling brave, you might experiment with run Eldamo using Tomcat instead Jetty. I don't upgrade the Eldamo tech stack very often because one of the main libraries I use (Saxon) has to be a very old version because the library author stopped supporting custom Java functions in the free version of Saxon.

**Comment by LuisMichaelis** [comment]
Hey! Thanks for the quick response. I was able to resolve that issue by using Eclipse (2019-06) and the Jetty plugin. It was probably the Jetty version because Gradle uses Jetty 6.1.25. I was not able to get Gradle to use another Jetty version and the newer Gretty plugin does also not work. So yeah I have no idea how to fix the build.gradle to account for that but Eclipse works. I'll try to get it working in IntelliJ IDEA and native Gradle but we'll see if i have any luck.

**Comment by ghchinoy** [comment]
Hi, @LuisMichaelis - I also had similar problems with gradle and jetty versions. I ended up using a containerized gradle 3.5 to build the project rather than trying to use gretty + later gradle versions. I'm not sure how this would integrate with IntelliJ or Eclipse from a development standpoint, having  Docker as the build step - maybe as you mentioned, via a script. My notes are here https://github.com/ghchinoy/eldamo-build

**Comment by pfstrack** [comment]
I will see if I can carve out some time this weekend to look at modernizing the Gradle build. Last weekend was Omentielva Toldea, so I was bust with that.
